import { type NextPage } from "next";
import Head from "next/head";
import { useWallet } from "@solana/wallet-adapter-react"

import Connect from "../components/connect";

const Home: NextPage = () => {
  const { connected } = useWallet()

  return (
    <>
      <Head>
        <title>Solana Core 1</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Solana <span className="text-[hsl(280,100%,70%)]">Core NFT </span>{" "}
            App
          </h1>
          {!connected && <div className="text-white text-2xl">Connect your wallet first</div>}
          
          <div className="flex max-w-xs flex-row gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
            <Connect />
          </div>
          {connected && <div className="text-white text-2xl">Start minting</div>}
          
        </div>
      </main>
    </>
  );
};

export default Home;
